name: test_conda_developer_installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        #python-version: [3.6,3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: MPIBGC-TEE/ComputabilityGraphs
        token: ${{ secrets.ACCESS_TOKEN }}
        #- uses: textbook/git-checkout-submodule-action@master
    - name: Set up conda 
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: |
        which python
        python --version
    - name: Install dependencies
      run: |
        sudo chmod -R 777 . 
        ./install_developer_conda.sh

    - name: Test with unittest
      run: |
        cd tests
        python -m unittest discover -t . -p 'Test*'
        
        
