# the name is actually important for the badge
name: conda_developer_installation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    
    steps:
    - uses: actions/checkout@v3
      #with:
        #repository: MPIBGC-TEE/ComputabilityGraphs
        #token: ${{ secrets.ACCESS_TOKEN }}
        #- uses: textbook/git-checkout-submodule-action@master
    - name: Set up conda 
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - name: Install dependencies
      run: |
        sudo chmod -R 777 . 
        conda install -y pip
        pip install git+https://git@github.com/MPIBGC-TEE/testinfrastructure.git#egg=testinfrastructure
        ./install_developer_conda.sh

    - name: Test with unittest
      run: |
        python -V
        cd tests
        python -m unittest discover -t . -p 'Test*'
        
        
